### ISSUE TITLE
Feature Request: Return host, port, and database as attributes in crunchybridge_clusterroles roles

### ISSUE THREAD

**Issue by kinghuang** [CrunchyData/terraform-provider-crunchybridge#12] opened 2024-07-19 21:10 UTC
The [crunchybridge_clusterroles data source](https://registry.terraform.io/providers/CrunchyData/crunchybridge/latest/docs/data-sources/clusterroles) provides database connection information for each role as `name`, `password`, and `uri`. It would be nice if it provided `host`, `port` and `database` too instead of just the `uri`, so that the values can be easily passed to other things such as the config of the [cyrilgdn/postgresql provider](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs).

I'm parsing the information out of the `uri` with the following regex.

```hcl
uri_parts = regex("^postgres://(?P<username>[^:]+):(?P<password>.+)@(?P<host>[^:]+):(?P<port>\\d+)/(?P<database>.*)$", data.crunchybridge_clusterroles.corpdoc.superuser.uri)
```

**Comment by wilybrace** [comment] 2024-07-19 21:17
Duplicate of #3

**Closed as completed by wilybrace** 2024-07-19 21:17 UTC
Labels: duplicate
